version: '3.4'
services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: springboot_java_rest
    ports:
      - "3308:3306" #host-por:container-port
    expose:
      - 3306 # to force, inside the container
    networks:
      - maus-network
  springboot-java-rest:
    image: themaus/springboot-java-rest
    restart: always
    build: ./springboot-java-rest
    working_dir: /springboot-java-rest
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/springboot_java_rest?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    command: mvn spring-boot:run
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - maus-network
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - maus-network
volumes:
  portainer_data:
networks:
  maus-network:
    driver: bridge